services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - "4533:4533"
    volumes:
      - ./appdata/navidrome:/data
      - ${NAS_PATH}/media/music:/music:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - home-network
    restart: always

networks:
  home-network:
    external: true
