networks:
  home-network:
    external: true

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./appdata/jellyfin:/config
      - ${NAS_PATH}/media/movies:/data/media/movies:ro
      - ${NAS_PATH}/media/tv:/data/media/tv:ro
      - ${NAS_PATH}/media/youtube:/data/media/youtube:ro
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096
    restart: always
    networks:
      - home-network

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    environment:
      TZ: ${TZ}
    volumes:
      - ./appdata/jellyseerr:/app/config
    ports:
      - 5055:5055
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: always
    networks:
      - home-network
