networks:
  home-network:
    external: true

services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      NETWORK_SHARE_MODE: "true"
      HARDCOVER_TOKEN: ${HARDCOVER_TOKEN}
    volumes:
      - ./appdata/config:/config
      - ${NAS_PATH}/calibre/ingest:/cwa-book-ingest
      - ${NAS_PATH}/calibre/library:/calibre-library
    ports:
      - 8014:8083
    restart: always
    networks:
      - home-network
