networks:
  home-network:
    external: true

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./appdata/radarr:/config
      - /mnt/downloads:/data/downloads
      - ${NAS_PATH}/media/movies:/data/media/movies
    ports:
      - 7878:7878
    restart: always
    networks:
      - home-network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./appdata/sonarr:/config
      - /mnt/downloads:/data/downloads
      - ${NAS_PATH}/media/tv:/data/media/tv
    ports:
      - 8989:8989
    restart: always
    networks:
      - home-network

  lidarr:
    image: lscr.io/linuxserver/lidarr:nightly
    container_name: lidarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./appdata/lidarr:/config
      - /mnt/downloads:/data/downloads
      - ${NAS_PATH}/media/music:/data/media/music
    ports:
      - 8686:8686
    restart: always
    networks:
      - home-network

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./appdata/bazarr:/config
      - ${NAS_PATH}/media/movies:/data/media/movies
      - ${NAS_PATH}/media/tv:/data/media/tv
    ports:
      - 6767:6767
    restart: always
    networks:
      - home-network
