networks:
  home-network:
    external: true

services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    environment:
      TZ: ${TZ}
      CRON_SCHEDULE: "@daily"
      RADARR_API_KEY: ${RADARR_API_KEY}
      SONARR_API_KEY: ${SONARR_API_KEY}
    volumes:
      - ./appdata/recyclarr:/config
    restart: always
    networks:
      - home-network
